-------------------------------------------------------------------------------
Test set: in.santhoshdevendran.door_step.TestCreateTask
-------------------------------------------------------------------------------
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.074 s <<< FAILURE! - in in.santhoshdevendran.door_step.TestCreateTask
in.santhoshdevendran.door_step.TestCreateTask.testCreateTaskWithValidData()  Time elapsed: 0.034 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception thrown: in.santhoshdevendran.door_step.exception.ValidationException: Due Date can not be in the Past
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:83)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:54)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:37)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3135)
	at in.santhoshdevendran.door_step.TestCreateTask.testCreateTaskWithValidData(TestCreateTask.java:35)
Caused by: in.santhoshdevendran.door_step.exception.ValidationException: Due Date can not be in the Past
	at in.santhoshdevendran.door_step.util.StringUtil.rejectIfInvalidDate(StringUtil.java:17)
	at in.santhoshdevendran.door_step.validation.TaskValidator.validate(TaskValidator.java:15)
	at in.santhoshdevendran.door_step.service.TaskService.create(TaskService.java:30)
	at in.santhoshdevendran.door_step.TestCreateTask.lambda$testCreateTaskWithValidData$0(TestCreateTask.java:36)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:50)
	... 16 more

